// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAXWSYCH2VrnZGGSerxBoY52L3cmZZzvwc",
      authDomain: "pizzasprintnotification.firebaseapp.com",
      projectId: "pizzasprintnotification",
      storageBucket: "pizzasprintnotification.firebasestorage.app",
      messagingSenderId: "412279854118",
      appId: "1:412279854118:web:34c54553c2ae0e402202e7",
      measurementId: "G-TJNKLLFJ04"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9CPOr97x7deaPsXPBSOLuVEJ4dwkqT7w',
    appId: '1:509013086734:android:1f6b01864e75953d64225f',
    messagingSenderId: '509013086734',
    projectId: 'device-streaming-46e05ee7',
    storageBucket: 'device-streaming-46e05ee7.firebasestorage.app',
  );

}